# Setup
title:            Akshay Aurora
description:      ''
baseurl:          /

author:
  name:           'Akshay Aurora'
  url:            https://twitter.com/akshayaurora

paginate:         5
paginate_path:    "/blog/page:num/"
permalink:        "/blog/:year/:month/:day/:title"

github: [metadata]

plugins:
  - jekyll-feed
  - jekyll-paginate
