permalink:  pretty
exclude: [scss]
markdown: maruku
pygments: true
baseurl: /

# Custom config
title: iAkshay
tagline: "Passionate web developer, Future engineer & Apple Fanboy"
url: http://www.iakshay.net


author:
 name: Akshay Aurora
 twitter: akshayaurora
 facebook: akshayaurora
 google_plus: 103665688081564203429
 github: iakshay
 email: me@iakshay.net
