permalink:  pretty
exclude: [scss]
markdown: kramdown
pygments: true
baseurl: /
timezone: Asia/Kolkata

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Custom config
title: iAkshay
tagline: "Passionate developer, Future engineer & Apple Fanboy"
url: http://www.iakshay.net


author:
 name: Akshay Aurora
 twitter: akshayaurora
 facebook: akshayaurora
 google_plus: 103665688081564203429
 github: iakshay
 email: me@iakshay.net
